### ISSUE TITLE
Refacto routing files

### ISSUE THREAD

**Issue by dwaps** [SullyvanBoulanger/beerbar-project-nodejs#26]
Il y a quelques différences de nommages au niveau des routes. Je propose d'harmoniser.

Actuellement on a 3 syntaxes --> `"/bars/:id"` ou `"/bars/:bar_id"` ou `"/bars/:id_bar"` (s'il y a des clés étrangères dans les modèles on accordera en fonction)

Si vous êtes d'accord, on met tout sur le modèle `bar_id,` ça vous va ? :)

**Comment by SullyvanBoulanger** [comment]
Ça me va perso, ça sera plus compréhensible comme ça :)
